#!/bin/bash

if [ $# -ne 2 ]; then
	echo "Usage $0 [InFile] [OutFile]"
fi

extractextension(){
	fullfile=$1
	filename=$(basename -- "$fullfile")
	extension="${filename##*.}"
	extension="${extension,,}"
	echo $extension
}

fullinfile=$1
fulloutfile=$2
extensionin=$(extractextension $fullinfile)
extensionout=$(extractextension $fulloutfile)

shift;
shift;

crf=18

while [ "$#" -gt 0 ]; do
	arg=$1
	echo "Processing $arg"
	case $arg in
		"-s"|"--small")
			crf=24
			;;
		*)
			echo "Unknown parameter $arg"
			;;
	esac
	shift
done

echo "${extensionin} -> ${extensionout}"

if [ "${extensionin}" == "mxf" ] || [ "${extensionin}" == "mov" ]; then
	if [ "${extensionout}" == "mp4" ]; then
		# Tested and works on mandulis (Without Audio)
		# ffmpeg -i ${fullinfile} -c:v libx264 -profile:v high -crf 18 -b 40k -pix_fmt yuv420p ${fulloutfile}
		# From the website
		ffmpeg -i ${fullinfile} -vf yadif -codec:v libx264 -crf $crf -bf 2 -flags +cgop -pix_fmt yuv420p -codec:a aac -strict -2 -b:a 384k -r:a 48000 -movflags faststart ${fulloutfile}	
	else
		echo "Conversion from ${extensionin} to ${extensionout} isn't supported yet."
	fi
elif [ "${extensionout}" == "mov" ]; then
	if [ "${extensionin}" == "mp4" ]; then
		ffmpeg -i ${fullinfile} -vcodec dnxhd -acodec pcm_s16le -s 1920x1080 -r 30000/1001 -b:v 36M -pix_fmt yuv422p -f mov ${fulloutfile}
	else
		echo "Conversion from ${extensionin} to ${extensionout} isn't supported yet."
	fi
else
	echo "Only conversion from or to .mov is supported"
fi

