#!/usr/bin/env bash

command=$1

echo $command



get_night() {
	OLDSTATE=$(dconf read /org/gnome/settings-daemon/plugins/color/night-light-enabled)
	echo "$OLDSTATE"
	exit $($OLDSTATE)
}

set_night() {
	STATE=$1
	cmd="dconf write /org/gnome/settings-daemon/plugins/color/night-light-enabled"

	if [[ "$STATE" = 'disable' ]]; then
		$cmd false
	else
		$cmd true
	fi
}

toggle(){
	STATE=$(get_night)
	if [[ "$STATE" = "false" ]]; then
		set_night enable
	else
		set_night disable
	fi
}


case $command in
	"get") get_night;;
	"enable") set_night enable;;
	"disable") set_night disable;;
	"toggle") toggle;;
esac

