git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  branchLogCmd: 'git log --graph --color=always --date=relative --oneline --decorate {{branchName}} --'
  allBranchesLogCmd: 'git log --graph --color=always --date=relative --oneline --decorate --all --'
gui:
  theme:
    lightTheme: false
    selectedLineBgColor: 
      - bold
os:
  editCommand: 'vim'
  editCommandTemplate: '{{editor}} +{{line}} {{filename}}'
